name: Publish to NPM

on:
  workflow_dispatch: # Allow manual runs
    inputs:
      version_type: # Let the user choose the version type
        description: "Version bump type: major, minor, or patch"
        required: true
        default: "patch"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Bump version and commit
        id: bump-version
        run: |
          npm version ${{ inputs.version_type }} --no-git-tag-version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Bump version to $(node -p "require('./package.json').version")"
          git tag v$(node -p "require('./package.json').version")
          git push origin HEAD --tags

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
